
CREATE TABLE HOSPITAL(ID SMALLINT PRIMARY KEY, NAME VARCHAR(100), CONTACTNO VARCHAR(100),GOVERNMENT VARCHAR(100) NULL,ADDRESS VARCHAR(100),
STATE VARCHAR(20) NOT NULL, DISTRICT VARCHAR(100) not null, WEBSITE VARCHAR(100) , HOSPITALTYPE VARCHAR(100), ADVANCEDFACILITY VARCHAR(100),DOCTORS SMALLINT);







 